name: .NET

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    
  workflow_dispatch:

env:
  SOLUTION: fx-events.sln

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Extract Version
        run: |
          echo "VERSION=${{ github['ref']/refs\/tags\/v/}}" >> $GITHUB_ENV
          echo "Ref: ${{ github.ref }}"
          echo "Version: $VERSION"
          
      - uses: microsoft/setup-msbuild@v1.0.2
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: '5.x'
      
      - name: Install dependencies
        run: nuget restore $SOLUTION

      - name: Build
        run: msbuild $SOLUTION -t:build
          
      - name: Pack Events.csproj
        run: nuget pack src/events/Events.csproj -Version $VERSION
      
      - name: Push Events.csproj
        run: nuget push src/events/Lusive.Events.$VERSION.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate
        
      - name: Pack Generator.csproj
        run: nuget pack src/generator/Generator.csproj -Version $VERSION
      
      - name: Push Generator.csproj
        run: nuget push src/generator/Lusive.Events.Generator.$VERSION.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate
