name: NuGet

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: '5.x'
      
      - name: Install dependencies
        run: nuget fx-events.sln restore

      - name: Build
        run: msbuild fx-events.sln -t:build
        
      - name: Extract Tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          
      - name: Pack Events
        run: nuget pack src/events/Events.csproj -Version ${VERSION}
      
      - name: Push Events
        run: nuget push src/events/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate
        
      - name: Pack Generator
        run: nuget pack src/generator/Generator.csproj -Version ${VERSION}
      
      - name: Push Generator
        run: nuget push src/generator/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate
